### ISSUE TITLE
Faltan descripciones en Excepciones

### ISSUE THREAD

**Issue by kiquebarbudo87** [davidroses02/JavaDoc#1]
[Decrementar](https://davidroses02.github.io/JavaDoc/GESTESIMAL/GESTESIMAL/decrementarNegativoException.html)
[PrecioNoValido](https://davidroses02.github.io/JavaDoc/GESTESIMAL/GESTESIMAL/PrecioNoValidoException.html)
[StockMaximo](https://davidroses02.github.io/JavaDoc/GESTESIMAL/GESTESIMAL/StockMaximoException.html)
[StockSeguridad](https://davidroses02.github.io/JavaDoc/GESTESIMAL/GESTESIMAL/StockSeguridadException.html)

@lmagarin

**Comment by davidroses02** [comment]
Issue corregido

**Comment by lmagarin** [comment]
en vez de issue corregido...
fix #1
